[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic[bedrock]>=0.67.0",
    "fastapi[standard]>=0.116.1",
    "mcp>=1.14.0",
    "python-dotenv>=1.1.1",
]
